Fix CD

diff --git a/.github/workflows/continuous_deployment.yml b/.github/workflows/continuous_deployment.yml
--- a/.github/workflows/continuous_deployment.yml
+++ b/.github/workflows/continuous_deployment.yml
@@ -6,34 +6,73 @@ on:
 
 jobs:
     deploy-to-staging:
-        uses: ./.github/workflows/deploy.yml
-        with:
-            environment: staging
-        secrets:
-            AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
-            AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
-            AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
-            EMAIL: ${{ secrets.EMAIL }}
-            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
-            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
-            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
-            SERVER_HOST: ${{ secrets.SERVER_HOST_STAGING }}
-            SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
-            SERVER_USER: ${{ secrets.SERVER_USER }}
+        runs-on: ubuntu-latest
+        steps:
+            - name: Deploy to staging
+              uses: appleboy/ssh-action@v1.2.2
+              with:
+                  host: ${{ secrets.SERVER_HOST_STAGING }}
+                  username: ${{ secrets.SERVER_USER }}
+                  key: ${{ secrets.SERVER_SSH_KEY }}
+                  script: |
+                      echo "Export GitHub secrets into environment variables"
+                      export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
+                      export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
+                      export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
+                      export EMAIL="${{ secrets.EMAIL }}"
+                      export AUTH_GITHUB_ID="${{ secrets.AUTH_GITHUB_ID }}"
+                      export AUTH_GITHUB_SECRET="${{ secrets.AUTH_GITHUB_SECRET }}"
+                      export AUTH_SECRET="${{ secrets.AUTH_SECRET }}"
+                      export DOMAIN_NAME="staging.matkassen.org"
+
+                      APP_DIR=~/matkassen
+                      if [ -d "$APP_DIR" ]; then
+                          echo "Pulling latest changes from the repository..."
+                          cd $APP_DIR
+                          echo "Discarding any local changes..."
+                          git reset --hard HEAD
+                          git clean -fd
+                          git pull origin main
+                          chmod +x update.sh
+                          ./update.sh
+                      else
+                          echo "App directory not found"
+                          exit 1
+                      fi
 
     manual-deploy-to-production:
         needs: deploy-to-staging
-        uses: ./.github/workflows/deploy.yml
-        with:
-            environment: production
-        secrets:
-            AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
-            AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
-            AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
-            EMAIL: ${{ secrets.EMAIL }}
-            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
-            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
-            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
-            SERVER_HOST: ${{ secrets.SERVER_HOST_PRODUCTION }}
-            SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
-            SERVER_USER: ${{ secrets.SERVER_USER }}
+        environment: production
+        runs-on: ubuntu-latest
+        steps:
+            - name: Deploy to production
+              uses: appleboy/ssh-action@v1.2.2
+              with:
+                  host: ${{ secrets.SERVER_HOST_PRODUCTION }}
+                  username: ${{ secrets.SERVER_USER }}
+                  key: ${{ secrets.SERVER_SSH_KEY }}
+                  script: |
+                      echo "Export GitHub secrets into environment variables"
+                      export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
+                      export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
+                      export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
+                      export EMAIL="${{ secrets.EMAIL }}"
+                      export AUTH_GITHUB_ID="${{ secrets.AUTH_GITHUB_ID }}"
+                      export AUTH_GITHUB_SECRET="${{ secrets.AUTH_GITHUB_SECRET }}"
+                      export AUTH_SECRET="${{ secrets.AUTH_SECRET }}"
+                      export DOMAIN_NAME="matkassen.org"
+
+                      APP_DIR=~/matkassen
+                      if [ -d "$APP_DIR" ]; then
+                          echo "Pulling latest changes from the repository..."
+                          cd $APP_DIR
+                          echo "Discarding any local changes..."
+                          git reset --hard HEAD
+                          git clean -fd
+                          git pull origin main
+                          chmod +x update.sh
+                          ./update.sh
+                      else
+                          echo "App directory not found"
+                          exit 1
+                      fi
